### ISSUE TITLE
I have changed PersistentVolumeClaims cause Error.

### ISSUE THREAD

**Issue by yaodwwy** [haoshuwei/gitlab-runner#1]
**k8s Log:**

Warning | Podrunner-ypqw71yt-project-... | pod has unbound immediate PersistentVolumeClaims (repeated 6 times) | FailedScheduling

**new pvc.yaml :**
---
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ template "gitlab-runner.fullname" . }}
  name: gitlab-runner-cache
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: nas
  volumeMode: Filesystem
  volumeName: gitlab-runner-cache
status: {}
```

Have I skim over something?
